- include: '{{ mongodb_init_system }}.yml'

- name: Wait for MongoDB to come up
  wait_for:
    port: '{{ mongodb_net_port }}'
    state: 'started'
    timeout: '{{ mongodb_wait_for_timeout }}'
  when: mongodb_wait_for
